### ISSUE TITLE
Support plantings with multiple crops

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_crop_plan#3]

**Comment by mstenta** [comment]
Related feedback from Cora at Wolfe's Neck:

> For plantings that have multiple varieties but are seeded/transplanted/harvested at the same time and location, it would be helpful to be able to treat these as a single crop. 
> - I believe there was the option for multiple varieties on the quick form where the planting had the varieties separated by commas? I think a similar function on the crop plan would work well!

**Comment by mstenta** [comment]
We are in the process of porting this module to farmOS v3, and moving it to https://www.drupal.org/project/farm_crop_plan, along with any open issues that are still relevant.

This issue will already be handled in the new version, so we can close it.
